=== michallaz/plepiseq_json/output_subschemes/infl_data.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Subschema for plepiseq output, Influenza specific data",
  "$comment": "Schemat dla outputu, informacja specyficzne dla wirusa grypy",
  "type": "object",
  "properties": {
    "reassortment_data": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "segment": {
            "type": "string",
            "$comment": "Nazwa segmentu wirusa grypy"
          },
          "reference_subtype": {
            "type": "string",
            "$comment": "Naza podtypu jaki został wybrany jako referencja dla danego segmentu"
          }
        },
        "required": [
          "segment",
          "reference_subtype"
        ]
      }
    },
    "typ": {
      "type": "string",
      "enum": [
        "A",
        "B",
        "unk"
      ],
      "$comment": "Informacja o typie wirusa grypy zidentyfikowanego w próbce, 'unk' tylko w przypadku gdy mamy reassortment tzn. nie wszystkie segmenty mają taki sam podtyp referencyjny. Wymagany."
    },
    "podtyp": {
      "type": "string",
      "enum": [
        "H1N1",
        "H3N2",
        "H5N1",
        "Yamagata",
        "..."
      ],
      "$comment": "Informacja o podtypie wirusa grypy zidentyfikowanego w próbce. Do uzupełnienia brakujące podtypy, tutaj wskazujemy to, co umie analizować pipeline, nie ma więc typów takich jak H16N10. Wymagany."
    },
    "bialka_grypa": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "protein_name": {
            "type": "string",
            "$comment": "Nazwa białka. Wymagany."
          },
          "protein_path": {
            "type": "string",
            "$comment": "Ścieżka do pliku tekstowego w formacie PDB ze strukturą. Wymagany."
          }
        },
        "required": [
          "protein_name",
          "protein_path"
        ]
      }
    },
    "opornosc_grypa": {
      "type": "array",
      "$comment": "Informacja o występowaniu mutacji wskazanych przez WHO jako powodujące oporność na leki przeciwwirusowe. Jest specjalne pole zbliżone do viral mutation data, ale grypa potrzebuje tutaj trochę innych rzeczy. Wymagany.",
      "items": {
        "type": "object",
        "properties": {
          "lek_nazwa": {
            "type": "string",
            "enum": [
              "Oseltamivir",
              "Zanamivir",
              "Peramivir",
              "Laninamivir",
              "Baloxavir"
            ],
            "$comment": "Nazwa leku przeciwwirusowego. Tylko te leki występują w tabeli WHO. Wymagany."
          },
          "lek_opornosc_status": {
            "type": "string",
            "enum": [
              "NI",
              "RI",
              "HRI",
              "unk"
            ],
            "$comment": "Nazewnictwo zgodnie z dokumentem WHO. W przypadku wielu mutacji oporność na lek determinowana jest mutacją o największym efekcie. Wymagany."
          },
          "lek_mutacje_numeracja_probka": {
            "type": "array",
            "$comment": "Lista mutacji zidentyfikowanych w próbce, które w dokumencie WHO są wypisane jako przebadane pod kątem powodowania oporności na dany lek antywirusowy. Pozycja mutacji jest określona według sekwencji białka z próbki. Oporność na leki oparta jest o badanie mutacji w białku. Wymagany.",
            "items": {
              "type": "object",
              "properties": {
                "mutacja_nazwa": {
                  "type": "string",
                  "$comment": "Nazwa mutacji, wersja skrócona",
                  "examples": [
                    "E23K"
                  ]
                },
                "mutacja_efekt": {
                  "type": "string",
                  "enum": [
                    "NI",
                    "RI",
                    "HRI"
                  ],
                  "$comment": "Efekt konkretnej mutacji ponownie w skali HRI, NI i RI"
                }
              },
              "required": [
                "mutacja_nazwa",
                "mutacja_efekt"
              ]
            }
          },
          "lek_mutacje_numeracja_reference": {
            "type": "array",
            "$comment": "Lista mutacji zidentyfikowanych w próbce, które w dokumencie WHO są wypisane jako przebadane pod kątem powodowania oporności na dany lek antywirusowy. Pozycja mutacji jest określona według sekwencji białka referencyjnego dla danego podtypu określonej przez WHO. Oporność na leki oparta jest o badanie mutacji w białku. Wymagany.",
            "items": {
              "type": "object",
              "properties": {
                "mutacja_nazwa": {
                  "type": "string",
                  "$comment": "Nazwa mutacji, wersja skrócona",
                  "examples": [
                    "E23K"
                  ]
                },
                "mutacja_efekt": {
                  "type": "string",
                  "enum": [
                    "NI",
                    "RI",
                    "HRI"
                  ],
                  "$comment": "Efekt konkretnej mutacji ponownie w skali HRI, NI i RI"
                }
              },
              "required": [
                "mutacja_nazwa",
                "mutacja_efekt"
              ]
            }
          },
          "lek_mutacje_numeracja_N2": {
            "type": "array",
            "$comment": "Lista mutacji zidentyfikowanych w próbce, które w dokumencie WHO są wypisane jako przebadane pod kątem powodowania oporności na dany lek antywirusowy. Pozycja mutacji jest określona według sekwencji referencyjnej białka NA z podtypu 2, stosowanego historycznie. Oporność na leki oparta jest o badanie mutacji w białku. Opcjonalny.",
            "items": {
              "type": "object",
              "properties": {
                "mutacja_nazwa": {
                  "type": "string",
                  "$comment": "Nazwa mutacji, wersja skrócona",
                  "examples": [
                    "E23K"
                  ]
                },
                "mutacja_efekt": {
                  "type": "string",
                  "enum": [
                    "NI",
                    "RI",
                    "HRI"
                  ],
                  "$comment": "Efekt konkretnej mutacji ponownie w skali HRI, NI i RI"
                }
              },
              "required": [
                "mutacja_nazwa",
                "mutacja_efekt"
              ]
            }
          }
        },
        "required": [
          "lek_nazwa",
          "lek_opornosc_status",
          "lek_mutacje_numeracja_probka",
          "lek_mutacje_numeracja_reference"
        ]
      }
    }
  },
  "required": [
    "reassortment_data",
    "typ",
    "bialka_grypa",
    "opornosc_grypa"
  ]
}

=== michallaz/plepiseq_json/output_subschemes_examples/infl_data_example.json
{
  "reassortment_data": [
    {
      "segment": "chr4_HA",
      "reference_subtype": "H1N1"
    },
    {
      "segment": "chr6_NA",
      "reference_subtype": "H1N1"
    }
  ],
  "typ": "A",
  "podtyp": "H5N1",
  "bialka_grypa": [
    {
      "protein_name": "HA",
      "protein_path": "/path/to/some.pdb"
    }
  ],
  "opornosc_grypa": [
    {
      "lek_nazwa": "Oseltamivir",
      "lek_opornosc_status": "HRI",
      "lek_mutacje_numeracja_probka": [
        {
          "mutacja_nazwa": "E23K",
          "mutacja_efekt": "HRI"
        }
      ],
      "lek_mutacje_numeracja_reference": [
        {
          "mutacja_nazwa": "E27K",
          "mutacja_efekt": "HRI"
        }
      ],
      "lek_mutacje_numeracja_N2": [
        {
          "mutacja_nazwa": "E27K",
          "mutacja_efekt": "HRI"
        }
      ]
    }
  ]
}
