=== michallaz/plepiseq_json/output_subschemes/sequencing_summary.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Subschema for plepiseq output, statistic information regarding reads.",
  "$comment": "Schemat dla outputu, statystyczne informacja o odczytach.",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "file_name": {
        "type": "string",
        "pattern": "^.*\\.fastq(.gz)?$",
        "$comment": "Nazwa pliku poddanego analizie. Wymagany."
      },
      "step_name": {
        "type": "string",
        "enum": [
          "pre-filtering",
          "post-filtering"
        ],
        "$comment": "Infomacja czy analiza dotyczyla odczytow oryginalnych czy po filtrowaniu Wymagany."
      },
      "error_message": {
        "type": "string",
        "$comment": "Dowoln tekst zwracany jako komunikat bledu podczas obliczen. Wymagany, jesli status to Blad"
      },
      "status": {
        "type": "string",
        "enum": [
          "tak",
          "nie",
          "blad"
        ],
        "$comment": "informacja czy udanie zakonczono obliczenia. Wymagany."
      },
      "number_of_reads_value": {
        "type": "number",
        "multipleOf": 1,
        "$comment": "Calkowita liczba odczytow. Wymagany."
      },
      "number_of_bases_value": {
        "type": "number",
        "multipleOf": 1,
        "$comment": "Calkowita ilosc zasad. Wymagany "
      },
      "reads_median_length_value": {
        "type": "number",
        "multipleOf": 0.01,
        "$comment": "Mediana dlugosci odczytow. Wymagany "
      },
      "reads_length_histogram_path": {
        "type": "string",
        "$comment": "Sciezka do pliku pozwalajacego narysowac histogram dlugosci odczytow. Zawartość pliku opisana w dokumentacji. Wymagany "
      },
      "reads_median_quality_value": {
        "type": "number",
        "multipleOf": 0.01,
        "$comment": "Mediana jakosci odczytow w skali PHRED+33. Wymagany "
      },
      "reads_quality_histogram_path": {
        "type": "string",
        "$comment": "Sciezka do pliku pozwalajacego narysowac histogram jakosci zasad w odczytach. Zawartość pliku opisana w dokumentacji. Wymagany "
      }
    },
    "required": [
      "file_name",
      "step_name",
      "status"
    ],
    "allOf": [
      {
        "if": {
          "properties": {
            "status": {
              "const": "tak"
            }
          }
        },
        "then": {
          "required": [
            "number_of_reads_value",
            "number_of_bases_value",
            "reads_median_length_value",
            "reads_length_histogram_path",
            "reads_median_quality_value",
            "reads_quality_histogram_path"
          ]
        },
        "else": {
          "required": [
            "error_message"
          ]
        }
      }
    ]
  }
}

=== michallaz/plepiseq_json/output_subschemes_examples/sequencing_summary_1.json
[
  {
    "file_name": "ala.fastq",
    "status": "tak",
    "step_name": "pre-filtering",
    "number_of_reads_value": 1000,
    "number_of_bases_value": 10000,
    "reads_median_length_value": 150,
    "reads_length_histogram_path": "/some/path",
    "reads_median_quality_value": 30,
    "reads_quality_histogram_path": "/some/path"
  },
  {
    "file_name": "ala2.fastq.gz",
    "status": "tak",
    "step_name": "pre-filtering",
    "number_of_reads_value": 10020,
    "number_of_bases_value": 100200,
    "reads_median_length_value": 1250,
    "reads_length_histogram_path": "/some/path",
    "reads_median_quality_value": 30,
    "reads_quality_histogram_path": "/some/path"
  },
  {
    "file_name": "forward.fastq",
    "status": "blad",
    "step_name": "post-filtering",
    "error_message": ""
  }
]
