=== michallaz/plepiseq_json/output_subschemes/viral_genome.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Subschema for plepiseq output, statistic information regarding viral genome.",
  "$comment": "Schemat dla outputu, statystyczne informacja o genomie wirusowym proponowanym dla probki.",
  "type": "object",
  "properties": {
    "komunikat_bledu": {
      "type": "string",
      "$comment": "Dowlny tekst zwracany jako komunikat bledu podczas obliczen. Wymagany, jesli status to Blad"
    },
    "status": {
      "type": "string",
      "enum": [
        "Tak",
        "Nie",
        "Blad"
      ],
      "$comment": "informacja czy policzono profil, niepoliczono, zwrocnono blad. Wymagany."
    },
    "genom_calkowita_dlugosc": {
      "type": "number",
      "$comment": "Calkowita dlugosc genomu. Wymagany."
    },
    "genom_srednie_pokrycie": {
      "type": "number",
      "multipleOf": 0.01,
      "$comment": "Srednie pokrycie dla zapronowanego genomu, z dokladnoscia maksymalnie do 2 miejsca po przecinku. Wymagany."
    },
    "genom_liczba_N": {
      "type": "number",
      "$comment": "Ilosc nieokreslonych nukleotydow zidentyfikowana w gnomie."
    },
    "genom_pokrycie_histogram": {
      "type": "array",
      "$comment": "Dane informujaca jakie w jakich zakresach jest pokrycie. Dane sa zbiorcze dla wszystkich segmentow.",
      "items": {
        "type": "object",
        "properties": {
          "zakres": {
            "type": "string",
            "$comment": "Zakres pokrycia. Wymagany."
          },
          "wartosc": {
            "type": "number",
            "$comment": "Ilosc pozycji w genomie, dla ktorych pokrycie jest w zakres. Wymagany."
          }
        },
        "required": [
          "zakres",
          "wartosc"
        ]
      }
    },
    "genom_pokrycie_barplot": {
      "type": "array",
      "$comment": "Dane informujaca o pokryciu na kazdej pozycji. Kazdy segment ma oddzielne dane.",  
      "items": {
        "type": "object",
        "properties": {
          "nazwa_segmentu": {
            "type": "string",
            "$comment": "Nazwa segmentu dla ktorego liczymy dane. Wymagany."  
          },
          "wartosc_plot_data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "pozycja": {
                  "type": "number"
                },
                "wartosc": {
                  "type": "number"
                }
              }
            },
            "required": [
              "pozycja",
              "wartosc"
            ]
          }
        },
        "required": [
          "nazwa_segmentu",
          "wartosc_plot_data"
        ]
      }
    },
    "genom_primer_usage": {
      "type": "array",
      "$comment": "Lista uzycia primerow.",
      "items": {
        "type": "object",
        "properties": {
          "primer_name": {
            "type": "string",
            "$comment": "Nazwa pary primerow."
          },
          "primer_usage": {
            "type": "number",
            "$comment": "Ilosc odczytow ktorych 5' lub 3' koniec mapuje sie na primer."
          }
        },
        "required": [
          "primer_name",
          "primer_usage"
        ]
      }
    }
  },
  "required": [
    "status"
  ],
  "allOf": [
    {
      "if": {
        "properties": {
          "status": {
            "const": "Tak"
          }
        }
      },
      "then": {
        "required": [
          "genom_calkowita_dlugosc",
          "genom_primer_usage",
          "genom_pokrycie_barplot",
          "genom_pokrycie_histogram",
          "genom_srednie_pokrycie",
          "genom_liczba_N"
        ]
      },
      "else": {
        "required": [
          "komunikat_bledu"
        ]
      }
    }
  ]
}

=== michallaz/plepiseq_json/output_subschemes_examples/viral_genome_example.json
{
  "status": "Tak",
  "genom_calkowita_dlugosc": 30000,
  "genom_srednie_pokrycie": 30.01,
  "genom_liczba_N": 10,
  "genom_pokrycie_histogram": [
    {
      "zakres": "10",
      "wartosc": 20
    },
    {
      "zakres": "11",
      "wartosc": 23
    }
  ],
  "genom_pokrycie_barplot": [
    {
      "nazwa_segmentu": "HA",
      "wartosc_plot_data": [
        {
          "pozycja": 1,
          "wartosc": 20
        }
      ]
    },
    {
      "nazwa_segmentu": "NA",
      "wartosc_plot_data": [
        {
          "pozycja": 1,
          "wartosc": 20
        },
        {
          "pozycja": 2,
          "wartosc": 22
        }
      ]
    }
  ],
  "genom_primer_usage": [
    {
      "primer_name": "Primer10",
      "primer_usage": 20
    }
  ]
}
