=== michallaz/plepiseq_json/output_subschemes/viral_mutations.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Subschema for plepiseq output, list of mutations with respect to the reference and their effect on proteins",
  "$comment": "Schemat dla outputu, informacja o mutacjach w probce w stosunku do referencji i ich potencjalnemu efektowi.",
  "type": "array",
  "items": {
    "properties": {
      "mutacja_lokalizacja": {
        "type": "string",
        "$comment": "Nazwa chromosomu/segmentu na ktorym zlokalizowano mutacje. Wymagany."
      },
      "mutacja_pozycja": {
        "type": "number",
        "minimum": 0,
        "$comment": "Pozycja (1-based) na ktorej wystepuje mutacja. Wymagany."
      },
      "mutacja_referencja": {
        "type": "string",
        "enum": [
          "A",
          "T",
          "G",
          "C"
        ],
        "$comment": "Allel referencyjny na danej pozycji na danym chromosomie. Wymagany."
      },
      "mutacja_probka": {
        "type": "string",
        "$comment": "Allel wystepujacy na danej pozycji na danym chromosomie w probce, alternatywnie w przypadku indeli stosujemy typowe dla nich nazwnictwo del12, ins15 itd. Wymagany."
      },
      "mutacja_gen": {
        "type": "string",
        "$comment": "Nazwa genu w jaki wpada mutacja. W przypadku mutacji intergenowych podajemy '-'. Wymagany."
      },
      "mutacja_efekt": {
        "type": "string",
        "$comment": "Efekt mutacji na strukture bialka, jesli wystepuje. Wymagany.",
        "examples": [
          "p.Phe924Phe",
          "p.Tyr145del"
        ]
      },
      "mutacja_typ": {
        "type": "string",
        "$comment": "Typ mutacji, missense, synonymous, frameshift itd. Wymagany."
      },
      "mutacja_pokrycie": {
        "type": "number",
        "minimum": 0,
        "$comment": "Ilosc odczytow mapujacych sie na pozycje mutacji. W przypadku delecji oznaczeniem jest '-'. Wymagany."
      },
      "mutacja_uzycie": {
        "type": "number",
        "multipleOf": 0.01,
        "maximum": 100,
        "minimum": 0,
        "$comment": "Procent odczytow niosacych wskazana mutacje. Wymagany."
      }
    },
    "required": [
      "mutacja_lokalizacja",
      "mutacja_pozycja",
      "mutacja_referencja",
      "mutacja_probka",
      "mutacja_gen",
      "mutacja_efekt",
      "mutacja_typ",
      "mutacja_pokrycie",
      "mutacja_uzycie"
    ]
  }
}

=== michallaz/plepiseq_json/output_subschemes_examples/viral_mutations_example.json
[
  {
    "mutacja_lokalizacja": "mn90.4",
    "mutacja_pozycja": 15738,
    "mutacja_referencja": "C",
    "mutacja_probka": "G",
    "mutacja_gen": "orf1ab",
    "mutacja_typ": "synonymous_variant",
    "mutacja_efekt": "p.Glu6597Glu",
    "mutacja_pokrycie": 100,
    "mutacja_uzycie": 99
  },
  {
    "mutacja_lokalizacja": "chr4_HA",
    "mutacja_pozycja": 157,
    "mutacja_referencja": "C",
    "mutacja_probka": "del11",
    "mutacja_gen": "HA",
    "mutacja_typ": "deletion",
    "mutacja_efekt": "p.Glu6597Glu",
    "mutacja_pokrycie": 76,
    "mutacja_uzycie": 86.82
  }
]
